/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_soul_jnidemo_BlurUtil */

#ifndef _Included_com_soul_jnidemo_BlurUtil
#define _Included_com_soul_jnidemo_BlurUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_soul_jnidemo_BlurUtil
 * Method:    blur
 * Signature: (Ljava/lang/Object;I)V
 */
JNIEXPORT void JNICALL Java_com_soul_jnidemo_BlurUtil_blur
  (JNIEnv *, jclass, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
